name: Update Activity Log and Deploy

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Run activity update script
        run: node .github/scripts/generate.js

      - name: Force Pages rebuild
        run: touch index.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "üîÅ Update README and force Pages rebuild"
          branch: main
          token: ${{ secrets.TOKEN }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
